name: pra_wo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  # CUDA-enabled PyTorch (12.1 build)
  - pytorch
  - torchvision
  - pytorch-cuda=12.1

  # Data & utilities
  - pandas=2.2.*
  - numpy=1.26.*
  - scikit-learn>=1.4
  - pyarrow
  - fastparquet
  - tqdm
  - tifffile
  - pyyaml
  - timm
  - pillow
  - matplotlib
  - seaborn

  # Pip section
  - pip
  - pip:
      - albumentations
      - opencv-python-headless
      - wandb
      - schedulefree
      - transformers
