method: bayes  # or grid or random
metric:
  name: Validation Accuracy
  goal: maximize

parameters:
  index: all_source_positive_control_named.pq
  epochs:
    values: 16
  batch_size:
    values: 32
  lr:
    min: 0.00001
    max: 0.01
  splits: 
    values: ["plates"]
  seed:
    values: 42
  architecture:
    values: ["ResNet50_Modified"]
  augmentation:
    parameters:
      resize:
        values: [[224, 224]]
      horizontal_flip_prob:
        values: [0.0, 0.5]
      vertical_flip_prob:
        values: [0.0, 0.5]
      noise_std: 
        values: [0.1, 0.4, 0.7]
      brightness_contrast_prob: 0.5
      plasma_shadow:
        prob: 0.5
        size: 256
        roughness: 3.0
        intensity_range:
          min: 0.3
          max: 0.7

command:
  - python
  - masterthesis/train.py
  - train
  - "--architecture=${architecture}"
  - "--epochs=${epochs}"
  - "--batch_size=${batch_size}"
  - "--lr=${lr}"
  - "--seed=${seed}"
  - "--augmentation={'resize': ${augmentation.resize}, 
    'horizontal_flip_prob': ${augmentation.horizontal_flip_prob}, 'vertical_flip_prob': ${augmentation.vertical_flip_prob}}', noise_std: ${augmentation.noise_std},
    'brightness_contrast_prob': ${augmentation.brightness_contrast_prob},
    'plasma_shadow'={'prob': ${augmentation.plasma_shadow.prob}, 'size': ${augmentation.plasma_shadow.size}, 
    'roughness': ${augmentation.plasma_shadow.roughness}, 'intensity_range': {'min': ${augmentation.plasma_shadow.intensity_range.min}, 
    'max': ${augmentation.plasma_shadow.intensity_range.max}}}"
  - "--index=${index}"
  - "--source_types=${source_types}"
  - "--splits=${splits}"
  - "--epochs=${epochs}"